version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: scrum-backend
    container_name: scrum-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongo-data:
