apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrum-frontend-deployment
  labels:
    app: scrum-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scrum-frontend
  template:
    metadata:
      labels:
        app: scrum-frontend
    spec:
      containers:
      - name: scrum-frontend
        image: akasbiacrpfa.azurecr.io/scrum-frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: scrum-secret
---
apiVersion: v1
kind: Service
metadata:
  name: scrum-frontend-service
spec:
  selector:
    app: scrum-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002  # Specify a NodePort or let Kubernetes assign one
  type: NodePort  # Change LoadBalancer to NodePort
